name: 'Continuous Integration'
on:
  push:
    branches:
      - $default_branch
  pull_request:
    branches:
      - $default_branch
  workflow_dispatch:

jobs:
  test:
    uses: accuracode/workflow-continuous-integration/.github/workflows/psalm.yml@9a4d1521ee23123d2a424ac929754038be2890ad
