name: 'Continuous Integration'
on:
  push:
    branches:
      - $default_branch
  pull_request:
    branches:
      - $default_branch
  workflow_dispatch:

jobs:
  test:
    uses: accuracode/workflow-continuous-integration/.github/workflows/psalm.yml@feature/add-new-psalm
    with:
      strict: false
      version: '4.27.0'
  sonar:
    needs:
      - test
    uses: accuracode/workflow-continuous-integration/.github/workflows/sonarcloud.yml@feature/add-new-psalm
    with:
      psalm-artifact-name: 'psalm-reports'
